Feature/inv 168/xml editor new tab
oat-sa/extension-tao-testqti pull request #1825
Opened 2020-06-12 09:35 UTC by tikhanovichA

2020-06-12 14:23 UTC, AndreyNegrov approved these changes
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-06-12 14:38 UTC, andreluizmachado requested changes
Just some small issues.

2020-06-12 14:38 UTC, andreluizmachado commented on actions/class.XmlEditor.php
> +
Is it possible to add strict_types in this and other files?

2020-06-12 14:38 UTC, andreluizmachado commented on actions/class.XmlEditor.php
> +   public function edit()
could u please add return type hint?

2020-06-15 08:47 UTC, tikhanovichA commented
> Just some small issues.

Fixed. Thanks!

2020-06-15 10:28 UTC, alexeyvy commented
**Review Checklist**
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
Unit tests pass. Integration tests fail, but it's not related with this PR.
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-06-15 10:29 UTC, alexeyvy approved these changes

2020-06-15 10:29 UTC, merged