Incorporate translations (received from BOSA) for the new strings in OAT
oat-sa/extension-tao-testqti pull request #2024
Opened 2021-05-31 11:14 UTC by habemuscode

**Ticket**

https://oat-sa.atlassian.net/browse/ADF-126

**Description**

As BOSA author
I would like the new functionality of Tabular Import to be provided with translations for French & Dutch
so that I can use it on my native language. 

**Acceptance Criteria** 

- AC1

```
GIVEN provided French translation for new keys introduced during Tabular Import feature implementation
   AND author is logged-in with preferred interface language set to French
THEN  TAO shall present Tabular Import related strings in French according to the translations provided
```

- AC2

```
GIVEN provided Dutch translation for new keys introduced during Tabular Import feature implementation
   AND author is logged-in with preferred interface language set to Dutch
THEN  TAO shall present Tabular Import related strings in Dutch according to the translations provided
```

**Environment**

_Pending..._

2021-06-01 11:14 UTC, gabrielfs7 approved these changes
Good job, @habemuscode ! :)

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-06-02 08:08 UTC, boajer approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-06-02 08:12 UTC, bziondik approved these changes
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2021-06-08 12:10 UTC, jsconan requested changes
Please avoid disclosing any internal info into public repository.
Please update the PR description with something generic.
Edit: moreover, the description is not accurate with what the PR is doing...

I think the existing translations should not be updated with customer specific. Instead, it should go to the customer related extension.

Please also check this other PR that is doing the same with regard to translations:
https://github.com/oat-sa/extension-tao-testqti/pull/2026#pullrequestreview-674030051

2021-06-08 12:10 UTC, jsconan commented on locales/fr-FR/messages.po
> +msgstr "Vous rencontrez une perte de connectivité prolongée. "
**nitpick:** please avoid putting specific content in generic extension.
This is a customer specific flavour, hence it should go to the customer's extension

2021-06-08 12:21 UTC, jsconan commented
Actually, I think this one is redundant with https://oat-sa.atlassian.net/browse/TR-1251.
You may eventually close this PR as it introduces a regression. Sorry for the mess :/

2021-06-09 11:47 UTC, habemuscode commented
Closing in favor of https://github.com/oat-sa/extension-tao-testqti/pull/2026

2021-06-09 11:47 UTC, closed without merging