TR-1869 Fix outcome variable calculation on test level timeout
oat-sa/extension-tao-testqti pull request #2078
Opened 2021-09-03 15:18 UTC by quintanilhar

Backport of [#2053](https://github.com/oat-sa/extension-tao-testqti/pull/2053) (TR-1432)

2021-09-06 12:11 UTC, wazelin requested changes
The older versions of extensions require a manual version bump in their [`manifest.json`](https://github.com/oat-sa/extension-tao-testqti/blob/hotfix/TR-1869/on-test-timeout-move-to-last-item/manifest.php#L56).

2021-09-07 07:00 UTC, quintanilhar commented
> The older versions of extensions require a manual version bump in their [`manifest.json`](https://github.com/oat-sa/extension-tao-testqti/blob/hotfix/TR-1869/on-test-timeout-move-to-last-item/manifest.php#L56).

Updated. :)

2021-09-08 09:35 UTC, alexeyvy approved these changes

2021-09-08 09:41 UTC, m-lagarde approved these changes

2021-09-08 10:11 UTC, merged