TR-2961 textReader asset post-processing
oat-sa/extension-tao-testqti pull request #2147
Opened 2021-12-14 16:54 UTC by poyuki

# [TR-2961](https://oat-sa.atlassian.net/browse/TR-2961)

## Summary
Need to create functionality which allow `CustomInteraction`(TextReader) assets post-processing 
 
## How to test
* update extension by branch
* create `item` with `Text Reader` with image
* create `test` with created in prev step `item`
* publish this `test` as local
* run published delivery and check in browser inspector image `src`

For affecting local `env` without `cdn` need to update `taoItems/models/classes/render/NoneItemReplacement.php`
by next code 
```
class NoneItemReplacement extends ConfigurableService implements ItemAssetsReplacement
{

    public function postProcessAssets($string)
    {
        return 'replaced-' . $string;
    }
}
```
depend on https://github.com/oat-sa/extension-tao-itemqti/pull/1975

2021-12-15 12:41 UTC, wazelin reviewed
Nice job!
A few inconsistent property annotation usages here and there (one line and multiple line), but that's pretty much it.

Will approve once deployed, tested and the dependency is and released.

2021-12-16 13:58 UTC, augustas approved these changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-12-16 14:28 UTC, wazelin requested changes
Will approve as soon as `oat-sa/extension-tao-itemqti` has been released, and a stable version set.

2021-12-16 16:14 UTC, wazelin approved these changes
- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2021-12-16 16:31 UTC, merged