fix: update raphael to 2.3.0
oat-sa/extension-tao-testqti pull request #2171
Opened 2022-01-12 10:35 UTC by krampstudio

Related to https://oat-sa.atlassian.net/browse/TR-3287

 - update rahpael to 2.3.0 `

2022-01-12 13:22 UTC, btamas requested changes

2022-01-12 13:22 UTC, btamas commented on views/package.json
> +    "@oat-sa/tao-test-runner-qti": "oat-sa/tao-test-runner-fe#fix/TR-3287/remove-source-based-npm-dependencies"
```suggestion
    "@oat-sa/tao-test-runner-qti": "oat-sa/tao-test-runner-qti-fe#fix/TR-3287/remove-source-based-npm-dependencies"
```

2022-01-13 07:24 UTC, btamas approved these changes

2022-01-13 07:24 UTC, btamas commented
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2022-01-13 09:42 UTC, bziondik approved these changes
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2022-01-13 15:05 UTC, merged