fix: categories assigned incorrectly in Test authoring
oat-sa/extension-tao-testqti pull request #2245
Opened 2022-04-13 10:38 UTC by Silvia-loza

Related to Issue: https://oat-sa.atlassian.net/browse/AUT-1459

Fix  categories assigned incorrectly during Test authoring

**Preconditions:**

- To have a class(folder) created in items with an added exposed property, defined as multiple choice:

![image](https://user-images.githubusercontent.com/60346520/163158916-4f4dde5a-1e98-4290-8c25-09ed0a3759d9.png)
Create various items with different properties from list:
![image](https://user-images.githubusercontent.com/60346520/163159198-85da62ab-087b-4118-80bc-63e9e66335b1.png)

**SETPS to test:**
• Checkout to branch: fix/AUT-1459/categories-assigned-incorrectly-during-test-authoring
• Create a new test and add the items one by one
•  Repeat this also for a section with subsections.
• Then check the section and item properties

**ACTUAL RESULT:**
The first item  properties are duplicated for all items and show as present for all at section level

**EXPECTED RESULT:**
All items keep their original properties and the section shows all properties present as partial, at section level

![image](https://user-images.githubusercontent.com/60346520/163160564-15d529a1-56bd-48a8-a1d3-70fad3f5f7b3.png)
![image](https://user-images.githubusercontent.com/60346520/163160861-4a15668c-1e29-4d1a-96ba-397f5dc8b3d9.png)
![image](https://user-images.githubusercontent.com/60346520/163161038-fe1c593d-9f00-4492-8d3e-8a67470ac027.png)

2022-04-13 12:02 UTC, bziondik requested changes
small improvements

2022-04-13 12:02 UTC, bziondik commented on views/js/controller/creator/views/section.js
>                              const categories = sectionCategory.getCategories(sectionModel);
`categories` isn't used, no need this line
<img width="554" alt="image" src="https://user-images.githubusercontent.com/25976342/163175369-872ddcb4-5625-4dfa-8de9-b7134b8c6881.png">

2022-04-13 12:02 UTC, bziondik commented on views/js/controller/creator/views/subsection.js
>                              const categories = sectionCategory.getCategories(subsectionModel);
the same

2022-04-13 12:02 UTC, bziondik commented on views/js/controller/creator/views/subsection.js
>                              //the itemRef should also "inherit" the categories set at the item level
```suggestion
                            // the itemRef should also "inherit" defaults categories set at the section level
```

2022-04-13 12:02 UTC, bziondik commented on views/js/controller/creator/views/section.js
>                              //the itemRef should also "inherit" the categories set at the item level
```suggestion
                            // the itemRef should also "inherit" default categories set at the section level
```

2022-04-13 12:27 UTC, bziondik approved these changes
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on playground (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2022-04-15 12:54 UTC, jsconan approved these changes
LGTM

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic

2022-04-19 08:55 UTC, merged