feature: add new event ResultTestVariablesAfterTransmissionEvent
oat-sa/extension-tao-testqti pull request #2425
Opened 2023-12-05 08:13 UTC by Karol-Stelmaczonek

Ticket: https://oat-sa.atlassian.net/browse/INF-235

## What's Changed

- add new event ResultTestVariablesAfterTransmissionEvent

2023-12-06 08:59 UTC, pribi commented
Can you please add test coverage to the new code created?

2023-12-06 15:59 UTC, Karol-Stelmaczonek commented on helpers/class.TestSession.php
> +        $scoreTotal = array_filter($event->getVariables(), function ($item) {
Done, thanks

2023-12-06 16:01 UTC, Karol-Stelmaczonek commented on helpers/class.TestSession.php
> +                if ($component instanceof OutcomeDeclaration) {
Thanks, done!

2023-12-07 12:43 UTC, pnal requested changes

2023-12-07 13:06 UTC, andreluizmachado commented on helpers/class.TestSession.php
> +        $this->getEventManager()->attach($event, [$this, 'attachToTransmissionEvent']);
The listeners of this event has to be registered via migrations

2023-12-07 17:56 UTC, Karol-Stelmaczonek commented on helpers/class.TestSession.php
> +        $this->getEventManager()->attach($event, [$this, 'attachToTransmissionEvent']);
I've rewritten the whole event logic here and it follows yours suggestions now.

2023-12-08 08:28 UTC, pnal approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2023-12-08 08:32 UTC, andreluizmachado commented on models/classes/eventHandler/ResultTransmissionEventHandler/ResultTransmissionEventHandler.php
> +    private function triggerTestVariablesRecorded(ResultTestVariablesTransmissionEvent $event): void
return type void will be deprecated on php8.1

2023-12-08 08:35 UTC, andreluizmachado commented on models/classes/eventHandler/ResultTransmissionEventHandler/ResultTransmissionEventHandler.php
> +    private function triggerTestVariablesRecorded(ResultTestVariablesTransmissionEvent $event): void
ok, just when Returning by reference

2023-12-08 09:55 UTC, Karol-Stelmaczonek commented on models/classes/eventHandler/ResultTransmissionEventHandler/ResultTransmissionEventHandler.php
> +    private function containsScoreTotal(ResultTestVariablesTransmissionEvent $event): array
Yes thats good point, changed

2023-12-08 11:08 UTC, andreluizmachado approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2023-12-08 12:15 UTC, pribi approved these changes
LGTM, but not tested.

2023-12-13 08:43 UTC, merged