chore: update methods to lodash 4 version
oat-sa/extension-tao-testqti pull request #2431
Opened 2023-12-28 11:21 UTC by taopkorczak

Related: https://oat-sa.atlassian.net/browse/ADF-1579

Update lodash methods to version 4.

2024-02-01 17:05 UTC, wazelin approved these changes

2024-02-01 18:59 UTC, wazelin requested changes
Please check the failing tests tomorrow, @taopkorczak.
And make sure to merge this PR after fixing the tests.

https://github.com/oat-sa/extension-tao-testqti/actions/runs/7744941999/job/21123704626

2024-02-01 18:59 UTC, wazelin commented on views/js/testRunner/testMetaData.js
> + * To clear all data related to current test_.every_id used <i>clearData</i> method.
```suggestion
 * To clear all data related to current test_call_id used <i>clearData</i> method.
```

2024-02-02 12:38 UTC, oatymart approved these changes
LGTM - fingers crossed...

2024-02-02 12:38 UTC, merged